using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public static class ItemDescriptionHolder 
{
	static Dictionary<int, string> m_descriptionID = new Dictionary<int, string>()
	{
		{0, "Type: Blaster\r\nBasic blaster firing supercharged bolts of ionised plasma"},
		{1, "Type: Shotgun\r\nArchaic, slug-based weapon that fires multiple shots in a wide arc. Effective against multiple small targets"},
		{2, "Type: Missile\r\nMissile launcher capable of both dumbfire and homing lock-on. Effective against either groups of foes or single large targets"},
		{3, "Type: Laser\r\nBeam weaponry created by firing focused light through radioactive crystals"},
		{4, "Type: Rapidfire\r\nAltered variant of the Pulse Blaster, modified for the highest rate of fire possible"},
		{5, "Type: Swarm\r\nAnti-ship system that fires multiple warheads in a wide arc. Can be dumbfired or locked on"},
		{6, "Type: Cannon\r\nRailgun firing solid metal shells capable of piercing targets if no kinetic barriers are present"},
		{7, "MISSINGITEM"},
		{8, "MISSINGITEM"},
		{9, "MISSINGITEM"},
		{10, "Type: Blaster\r\nThe mkII blaster, featuring an experimental method of supercharging the plasma shots"},
		{11, "Type: Shotgun\r\nThe mkII shotgun manages to sustain the same amount of damage per pellet, while improving the number of pellets fired"},
		{12, "Type: Missile\r\nThe 'Meteor' was named for it's ability to destroy smaller targets in a single shot"},
		{13, "Type: Laser\r\nExperimental beam developed by the self-proclaimed 'King' of Vorcas VI, shortly before he was violently deposed"},
		{14, "Type: Rapidfire\r\nAn upgraded emitter, with the focus still on rate of fire. Popularised by the film 'Lunar Pirates'"},
		{15, "Type: Swarm\r\nThe weapon for which the class is named. A staple element of any anti-ship formation"},
		{16, "Type: Cannon\r\nImproved railgun, featuring a 40-stage acceleration process. Used by the Leoticus band of raiders, hence it's name"},
		{17, "MISSINGITEM"},
		{18, "MISSINGITEM"},
		{19, "MISSINGITEM"},
		{20, "Type: Blaster\r\nElite-tier blaster. The bolts are generated through an experimental 'pulsating' method, with produces much more damaging shots"},
		{21, "Type: Shotgun\r\nBlack-market shotgun weapon created through destabalising the central matrix. Highly volatile"},
		{22, "Type: Missile\r\nA launcher and munition replicator rolled into one. Fires two high explosive warheads."},
		{23, "Type: Laser\r\nVery rare laser developed with exotic minerals in the focusing chamber. Nicknamed 'blade' due to it's propensity to cut straight through ships"},
		{24, "Type: Rapidfire\r\nSought-after emitter that unleashes a literal torrent of blaster fire. Popular with mercenary bands due to it's ease of use"},
		{25, "Type: Swarm\r\nHighly destructive swarm launcher. Banned in several sectors due to many incidents of accidental property destruction during use"},
		{26, "Type: Cannon\r\nExperimental railgun developed by Laltek Industries. According to advertising, capable of destroying Titan-class cruisers in a few shots"},
		{27, "MISSINGITEM"},
		{28, "MISSINGITEM"},
		{29, "MISSINGITEM"},
		{30, "Type: Tactical Shield\r\nLow-capacity, fast recharge barrier. Excels at hit-and-run skirmishes. Often used on scout vessels"},
		{31, "Type: Balanced Shield\r\nMiddle of the line barrier. Equipped to most space-faring vessels as a balanced solution to recharge and capacity"},
		{32, "Type: Endurance Shield\r\nHigh-capacity, slow recharge barrier. Excels at surviving extended battles. Often used on capital ships"},
		{33, "MISSINGITEM"},
		{34, "MISSINGITEM"},
		{35, "MISSINGITEM"},
		{36, "MISSINGITEM"},
		{37, "MISSINGITEM"},
		{38, "MISSINGITEM"},
		{39, "MISSINGITEM"},
		{40, "Type: Tactical Shield\r\nImproved fast barrier, adapted from alien technology during Humanity's ascent. Often found on lone wolf mercenary vessels"},
		{41, "Type: Balanced Shield\r\nRecently developed, soon-to-bo standard issue barrier for human military vessels. All-round effective shield solution"},
		{42, "Type: Endurance Shield\r\nA heavy shield, often utilised on so-called 'shield ships', that act as a movable barrier for smaller ships to take cover behind"},
		{43, "MISSINGITEM"},
		{44, "MISSINGITEM"},
		{45, "MISSINGITEM"},
		{46, "MISSINGITEM"},
		{47, "MISSINGITEM"},
		{48, "MISSINGITEM"},
		{49, "MISSINGITEM"},
		{50, "Type: Tactical Shield\r\nThe ultimate rapid barrier solution. Has such a fast recharge system, that the parent ship is only vulnerable for a short amount of time"},
		{51, "Type: Balanced Shield\r\nTop of the range balanced shield. Rumours about the shield suggest it has saved small ships from collisions with much larger vessels"},
		{52, "Type: Endurance Shield\r\nLegendary endurance shield. Famously used by the mercenary Tal'Kuro when it saved his vessel from a capital-class cannon shot"},
		{53, "MISSINGITEM"},
		{54, "MISSINGITEM"},
		{55, "MISSINGITEM"},
		{56, "MISSINGITEM"},
		{57, "MISSINGITEM"},
		{58, "MISSINGITEM"},
		{59, "MISSINGITEM"},
		{60, "Type: Agile Engine\r\nBasic engine with multiple thurster outlets across the hull. Gives the ship very high manoeuvrability, but a slower forward speed"},
		{61, "Type: Standard Engine\r\nStandard-issue engine with a balance between forward speed and non-forward agility"},
		{62, "Type: Drag Engine\r\nTuned engine that reroutes most of the non-rear thrusters to to aid forward speed at the expense of agility"},
		{63, "MISSINGITEM"},
		{64, "MISSINGITEM"},
		{65, "MISSINGITEM"},
		{66, "MISSINGITEM"},
		{67, "MISSINGITEM"},
		{68, "MISSINGITEM"},
		{69, "MISSINGITEM"},
		{70, "Type: Agile Engine\r\nPrototype agility engine co-developed by Gosforth Solutions and King Industries. Very agile, excels at tasks involving asteroid fields"},
		{71, "Type: Standard Engine\r\nUpgraded standard engine system. Often used on military vessels due to its all-round capabilities"},
		{72, "Type: Drag Engine\r\nNamed for the ancient Greek messenger god due to its widespread use on courier vessels. Very effective at escaping danger if needs be"},
		{73, "MISSINGITEM"},
		{74, "MISSINGITEM"},
		{75, "MISSINGITEM"},
		{76, "MISSINGITEM"},
		{77, "MISSINGITEM"},
		{78, "MISSINGITEM"},
		{79, "MISSINGITEM"},
		{80, "Type: Agile Engine\r\nThe product of 'Project X', a co-development project between six different species' research departments. The prohibitive cost makes this engine rare"},
		{81, "Type: Standard Engine\r\nExperimental thruster system developed by a secret technology cult. Codenamed 'Celadon' due to the blue-shift from the engine's energy pattern"},
		{82, "Type: Drag Engine\r\nUltra-rare engine focused on speed. Made of only the most expensive materials in the most advanced of factories"},
		{83, "MISSINGITEM"},
		{84, "MISSINGITEM"},
		{85, "MISSINGITEM"},
		{86, "MISSINGITEM"},
		{87, "MISSINGITEM"},
		{88, "MISSINGITEM"},
		{89, "MISSINGITEM"},
		{90, "Type: Light Plating\r\nStripped-down version of standard plating. Makes the craft much lighter and more agile, but reduces the maount of damage it can take"},
		{91, "Type: Medium Plating\r\nStandard-issue armour that provides a balance between mobility and survivability"},
		{92, "Type: Heavy Plating\r\nAdditional armour plating that increases the punishment a vessel can take, but hampers it's movement"},
		{93, "MISSINGITEM"},
		{94, "MISSINGITEM"},
		{95, "MISSINGITEM"},
		{96, "MISSINGITEM"},
		{97, "MISSINGITEM"},
		{98, "MISSINGITEM"},
		{99, "MISSINGITEM"},
		{100, "Type: Light Plating\r\nLightweight alloy allows this armour to have similar protection to standard issue armour while keeping the craft more manoeuvrable"},
		{101, "Type: Medium Plating\r\nAdvances in armour design have allowed this plating arrangment to provide more protection than standard armour while maintaining agility"},
		{102, "Type: Heavy Plating\r\nArmour that copies the Vesparian armour layout. Centered around a single moulded sheet of armour which hampers vessel movement"},
		{103, "MISSINGITEM"},
		{104, "MISSINGITEM"},
		{105, "MISSINGITEM"},
		{106, "MISSINGITEM"},
		{107, "MISSINGITEM"},
		{108, "MISSINGITEM"},
		{109, "MISSINGITEM"},
		{110, "Type: Light Plating\r\nSpecialised stealth armour utilised by Maiorian ambush parties. The ability to utilise it's cloaking system was sadly lost in the retrofit to human ships"},
		{111, "Type: Medium Plating\r\nA combination of both the lightweight alloy armour and untraditional armour placement techniques. Results in very strong all-round armour"},
		{112, "Type: Heavy Plating\r\nArmour fashioned from the very rare (but very heavy) metal 'Impervium'. Unbeatable protection, but at a serious cost to agility"},
		{113, "MISSINGITEM"},
		{114, "MISSINGITEM"},
		{115, "MISSINGITEM"},
		{116, "MISSINGITEM"},
		{117, "MISSINGITEM"},
		{118, "MISSINGITEM"},
		{119, "MISSINGITEM"},
		{120, "Type: Capital Weapon\r\nStandard anti-ship turrets for larger vessels. Will attempt to lead targets to ensure accuracy"},
		{121, "Type: Capital Weapon\r\nImproved default turret with additional barrels, for faster rate of fire"},
		{122, "Type: Capital Weapon\r\nAnti-swarm weapon designed to affect a large area around the target with damage. Effective against large groups of both foes and asteroids"},
		{123, "Type: Capital Weapon\r\nPowerful focused light beam that excels at destroying targets close to the attached vessel"},
		{124, "Type: Capital Weapon\r\nFires multiple homing warheads. Can easily take down larger ships with a volley of explosive missiles"},
		{125, "Type: Capital Weapon\r\nA body-modifying weapon system that replaces portions of the fuselage with huge missile ports. Fires large, homing warheads at nearby targets"}
	};

	public static string GetDescriptionFromID(int id)
	{
		string output = "";
		output = m_descriptionID[id];

		if(output == "MISSINGITEM")
		{
			return null;
		}
		else
		{
			return output;
		}
	}
}
